import Head from "next/head";
import React from "react";
import Base from "../layouts/Base";
import { Container, Typography } from "@mui/material";

export default function Soonabots() {
  return (
    <>
      <Head>
        <title>Soonabots</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base>
        <Container maxWidth="md">
          <Typography variant="h1">Soonabots</Typography>
        </Container>
      </Base>
    </>
  );
}
